name: Build

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
          
      - uses: sonarsource/sonarqube-scan-action@master
        with:
          projectBaseDir: .
          args: > 
            -Dsonar.projectKey=hoangbvh-test
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
